### ISSUE TITLE
Page liste Questions cassée

### ISSUE THREAD

**Issue by nicolasleger** [railsfrance/railsfrance.org#126]
Par le lien du header nous arrivons sur http://www.railsfrance.org/questions qui nous renvoie une erreur.
À noter que le rendu Atom fonctionne http://www.railsfrance.org/questions donc cela doit provenir du template HAML `app/views/questions/index.html.haml`. Le rendu d'une question fonctionne.

**Comment by pi3r** [comment]
Yeah... I'm working on https://github.com/railsfrance/railsfrance.org/pull/123 (which is the deployed branch) but I couldn't get a green build. I'll try to have a look this week end. Thanks!

**Comment by pi3r** [comment]
works now... looks like I'm only having a look every 3 months...
