### ISSUE TITLE
Apparition de code Ruby sur la page

### ISSUE THREAD

**Issue by mosleymos** [railsfrance/railsfrance.org#128]
Sur cette url l'on voit le code en clair de l'application
Il s'agit d'une offre de mediatech

http://www.railsfrance.org/jobs/ruby-on-rails-front-back-h-f

Cordialement
![screenshot from 2015-09-30 11 22 15](https://cloud.githubusercontent.com/assets/4508460/10189227/4b26f2e2-6765-11e5-9fef-2d2cb2184057.png)

**Comment by pi3r** [comment]
Hey @mosleymos, je pense que c'est leur façon "geek" de poster l'annonce. Le titre de l'issue m'a fait bien peur :)

**Comment by mosleymos** [comment]
C'est vrai que maintenant je regarde de plus près, c'est plus marrant.

Merci 
Cordialement
